### ISSUE TITLE
Auth - Login Workflow

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#11]
As a user, I would like to log in to Wombats using my Github account. 

*AC:*

- When the user attempts to preview a game, an alert is presented prompting the user to login to continue 
- When the user attempts to view "My Games", text on the screen displays "Please log in to view your games!"
- Github auth workflow is initiated when the user clicks "Log In" in the navbar
- If auth is successful, user is returned to the Available Games screen
- If auth is unsuccessful, user is stranded on Github screen (outside of our control)
- While user is logged in, "My Wombats" is displayed instead of "Log In" in navbar

*API Dependencies:*

136: Auth - Github Workflow 
137: Auth - Create User
138: Auth - Get Current User"

**Comment by morganedmonds** [comment]
Per @emilyseibert , we need to test with new auth PR

**Comment by morganedmonds** [comment]
Some observations on this ticket as it's currently implemented:

Attempting to access games displays the message "please log in to view your games" 
There is no Github handle displayed 
Successful auth returns the user to the Open Games screen as expected
Auth flow functions as expected 
My Wombats and Login button toggle as expected 

This may change as we update the games screen and potentially implement the landing page. Looks good based on current scope, moving to closed.
