### ISSUE TITLE
Framework - User Navbar

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#12]
AC:

- For V1 only Games, Config and My Wombats are displayed and active
- My Wombats toggles to "Log In" when a user is not logged in
- Config is available only to admin and event coordinators
- Users is available only to admin

Zeplin: https://zpl.io/17G3Lb

**Comment by emilyseibert** [comment]
dependent on user roles in db @oconn @morganedmonds
