### ISSUE TITLE
[BUG] Hover after Select Color in Join Modal Glitchy

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#123]
<img width="375" alt="screen shot 2017-02-17 at 3 38 21 pm" src="https://cloud.githubusercontent.com/assets/16102717/23082384/26724ee6-f527-11e6-9ec8-49d62e718d39.png">

Border should be all around or not show on selected bots. Confirm with Jess

**Comment by morganedmonds** [comment]
I'm seeing no border shown on hover after selecting a Wombat, looks good to me. Moving to closed.
