### ISSUE TITLE
Games - Lobby Revised Designs

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#124]
AC:

* "Open" section includes all games EXCEPT closed
* "Finished" section includes only closed games
* Checking "show my games" applies a filter that displays only games that have been joined by the current user; empty state matches designs in Zeplin

Out of Scope:
* Game cards and card hover states are in separate tickets
* Sorting game cards will go into a different ticket

Zeplin: 
Open: https://zpl.io/21Hqcx
Finished: https://zpl.io/DmyEr
No Open Games: https://zpl.io/Z4F9Fg
No Joined Games: https://zpl.io/Kh8pd

**Comment by morganedmonds** [comment]
Updated AC per new reqs.

**Comment by emilyseibert** [comment]
:active-intermission ? and sort on api? 

otherwise complete

**Comment by morganedmonds** [comment]
The only issue I'm seeing here is the game sort, which Emily has called out. I broke that piece out into another ticket, #150. Moving to design review.

**Comment by emilyseibert** [comment]
@morganedmonds this should be sorted already but...

open: latest open time (most in the past) at the top 
finished: most recently ended at the top (based on :game/end-time)
