### ISSUE TITLE
Games - Game State Toggle

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#13]
As a user, I would like to filter between Available" and "My Games" by hovering over "Games" in the nav bar.

**AC:**
* A dropdown menu with "Available" and "My Games" options is displayed when hovering over Games in the nav bar
* The number of corresponding games is included in parenthesis next to each option
* The games screen is displayed with all games in the chosen category upon clicking on an option

**Zeplin:**
https://zpl.io/21Hqcx

**API Dependencies:**
114: Games - Game Transitions

**Comment by morganedmonds** [comment]
Because of new designs, this is a duplicate of #32 - closing
