### ISSUE TITLE
Arena - Canvas Display

### ISSUE THREAD

**Issue by dehli** [willowtreeapps/wombats-web-client#131]
## Problem
Currently, the canvas is hardcoded to have a width and height of 600 pixels. We need the canvas to handle different screen sizes, different arena aspect ratios, and be able to support very large maps.

**Comment by morganedmonds** [comment]
For this ticket, we're only supporting square arenas.

**Comment by morganedmonds** [comment]
We're still seeing issues in Safari (#290), but this looks good in Chrome.
