### ISSUE TITLE
[Refactor] Make it so modals use flex-box

### ISSUE THREAD

**Issue by dehli** [willowtreeapps/wombats-web-client#137]
## Problem
Our current implementation of modals requires special cases for different height modals. If we were to switch to flex-boxes it will make the code cleaner.

**Comment by emilyseibert** [comment]
- different height modals are still centered
- wrapping bug where winner modal over arena isn't centered into this ticket

**Comment by morganedmonds** [comment]
I'm not able to test this just yet since i'm not seeing the winner modal displayed anymore.
