### ISSUE TITLE
Game Lobby - Pagination

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#14]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
Infinite scroll refresh on the games lobby for both the open and finished sections

**- Why you need it**
Allow a user to view all games

**- How it should work**
Infinite scroll refresh 

Include any relevant documentation that will help prompt a discussion!

**Comment by morganedmonds** [comment]
The is going into V2.

**Comment by emilyseibert** [comment]
Dupe, closing
