### ISSUE TITLE
[REFACTOR] Build Game Status Query

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#146]
Use a pretty set and not strings to generate status query

**Comment by emilyseibert** [comment]
[`join`](https://clojuredocs.org/clojure.string/join) would be a good idea for this

**Comment by morganedmonds** [comment]
@emilyseibert is there any way for me to test this?

**Comment by emilyseibert** [comment]
nope, just as long as the games come back for you
