### ISSUE TITLE
[Feature] Winner modal support ties

### ISSUE THREAD

**Issue by dehli** [willowtreeapps/wombats-web-client#147]
## Problem
Currently, there can only be one winner (the modal just shows the first winner in the case of ties).

**Comment by morganedmonds** [comment]
This looks good to me. See screenshot below. Moving to design review. 

<img width="1680" alt="screen shot 2017-03-01 at 9 38 55 am" src="https://cloud.githubusercontent.com/assets/25081733/23464541/450664ba-fe4a-11e6-88ef-174d26ed217f.png">
