### ISSUE TITLE
[BUG] Login sometimes doesn't work without /#/ appended

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#148]

**Comment by emilyseibert** [comment]
To replicate:
* Open up home page in incognito tab
* Go to Application in Dev Tools
* Add a fake token value
* Refresh page

**Comment by emilyseibert** [comment]
Fixed with API throwing error if /api/v1/self doesn't have token credentials

**Comment by morganedmonds** [comment]
Looks good, moving to closed. Tested per  the repro steps above.
