### ISSUE TITLE
Game Lobby - Search

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#15]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
As a user, I would like to search for a game.

**- Why you need it**
As our list of games grows, users will want to search for specific games to join, watch or replay.

**- How it should work**

* Search field displays for both the open and finished sections
* No results found matches design in Zeplin
* Search by game name (anything else?)

**- Zeplin**
https://zpl.io/Z2sv0ei

**- Open Questions**
* Can we do partial search queries, eg. "gam" instead of "game"?
* Can we search by other game attributes, such as private or public?
* Can we dynamically return search results?

**Comment by morganedmonds** [comment]
Search is going to be a V2 feature.

**Comment by emilyseibert** [comment]
Dupe closing
