### ISSUE TITLE
Games - Sort Game Cards

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#150]
AC:

Games are sorted by start time; for open, the closest start time; for closed, the most recent start time

**Comment by emilyseibert** [comment]
This needs to be  updated and possible QA'd again

**Comment by morganedmonds** [comment]
@emilyseibert I think I'm confusing myself about the sorting rules, it looks strange to me right now (in part because we're still able to create games in the past). Can we take a look at it together tomorrow?

**Comment by morganedmonds** [comment]
Did more testing, this looks good. Just something to note - if a game is scheduled to start in the past, it will show up before those coming up (which makes sense given the implementation, but may seem weird to the average user). 

Moving to closed.
