### ISSUE TITLE
Inline Errors for Modals

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#154]
Probably would be good to create an accessor to pull out error code from the error response.

**Comment by emilyseibert** [comment]
from oconn: One thing to note though. I had to move some of the db transactions to the datomic transactor which means we lose error codes for specific transactions. We still return an error in the same shape but the code will be replaced by :player-join-db-fn for all errors thrown inside the transactor. I can work with you whenever you have time to force trigger any of these errors if that will be helpful.

**Comment by emilyseibert** [comment]
- General server side errors should be below title in red
- Game Full error and Game Has Started error in new modal
- Server side error but about a field (wombat-color) should be shown like inline error
- Inline errors from validation checks should be under content, in red, red border outline

**Comment by oconn** [comment]
@emilyseibert Is this blocked by the changes we were working on today? Those are in https://github.com/willowtreeapps/wombats-api/pull/291

**Comment by emilyseibert** [comment]
yup just waiting for the merge

**Comment by emilyseibert** [comment]
client side errors complete in PR #192
