### ISSUE TITLE
Preview - Show Join/Hide Chat

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#156]
AC:

* If the user has not joined the game, the join button is displayed and chat is hidden
* Once the user has joined the game, the join button is hidden and chat is displayed

**Comment by dehli** [comment]
Hiding chat is currently complete, however join button isn't fully implemented. Quoted from #206:

> Currently, if you start the app on a game, the join game button won't properly display if it's a private game. This will require some API changes and then client changes to reflect those changes. I will address that in the next PR (and make a note in ticket #156).

**Comment by dehli** [comment]
Note from PR #206:

> I'll be refactoring how stats work in the next PR (so that we can use the same utils from games here). Added a note in #156 to make sure I don't forget.

**Comment by oconn** [comment]
@dehli What are the required API changes for support?

**Comment by dehli** [comment]
I want to refactor the game socket payload so it matches the get request more closely (that way the same store can be used). It wont take too long to implement @oconn

**Comment by morganedmonds** [comment]
These seems to be working as expected, moving to design review for Jesse to take a look at it before closing

**Comment by emilyseibert** [comment]
Removing design review because jesse saw this on Friday. He created a new ticket for the join modal from this view.
