### ISSUE TITLE
Games - Cards

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#16]
**AC:**
- Game Card displays  arena image, game type, number of rounds, grid size and arena icons (Wombat, Zakano, Food, Poison)
- The frequency of the arena element is displayed below the icon (number of elements)
- For games that the user has joined, show the Wombat player icon in the corner of the card
- For games in pending-open, show default card
- For games in pending-closed, show "FULL" over arena image
- For games in active or active-itermission, show "ACTIVE" over arena image
- For games in closed AND in still in the open section, show "FINISHED" over arena image (NOTE: this may not be necessary/possible)
- For games in Finished section, show default card

**Zeplin:**
Open: https://zpl.io/21Hqcx
Finished: https://zpl.io/DmyEr
No Open Games: https://zpl.io/Z4F9Fg
No Joined Games: https://zpl.io/Kh8pd

**Out of Scope:**
Card hover states are broken out in separate ticket.

Countdown timer (or any scheduled time) is slated for a future version.

**Comment by morganedmonds** [comment]
The AC for this ticket needs to be updated based on our current implementation of arena element frequency. We should discuss the best way to represent that information since it should be dynamic.

**Comment by emilyseibert** [comment]
Need numerical ranges to determine if high/med/low frequency.

**Comment by morganedmonds** [comment]
Emily will take a screenshot of current arena to fill static image.

**Comment by morganedmonds** [comment]
Need to update AC

**Comment by morganedmonds** [comment]
I think this has already been called out, games with an active-intermission state are not shown in the Open section. Kicking this back to Ready to get that piece done.

**Comment by morganedmonds** [comment]
this looks good, moving to closed.
