### ISSUE TITLE
Design Review - Game Lobby Updates

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#165]
A few updates need to be made to the game lobby after reviewing with Jesse & Bekah:

* Fill game cards left to right, top to bottom
* Change plurality for # Rounds in case of 1 Round
* Style Join button with hover state
* Enlarge arena element icons on game card
* Make “Show my games” text next to checkbox clickable (in addition to checkbox)
* Center lock icon with "Join" in button

NOTE: this is a big ticket, please let me know if it make sense to break out any (or all) of the pieces into separate tickets.

**Comment by emilyseibert** [comment]
* Style Join button with hover state in PR #167
* Make "Show my games" text clickable in PR #167

**Comment by morganedmonds** [comment]
This all looks good to me, moving to design review for Jesse to confirm before closing.
