### ISSUE TITLE
Games - Cards - Hover States

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#19]
As a user, I would like to view and hover over a game card to see available actions for the game.

**AC:**
- For pending-open games, Join button displays on hover
- For private and pending-open games, Join button displays with lock icon
- All games display border on hover
- Clicking on a game card (outside of a Join button) navigates the user to the game screen

**Zeplin:**
 https://zpl.io/21Hqcx

**API Dependencies:**
155: Games - Get Open Private Games
156: Games - Get Ongoing Games
157: Games - Get Closed Games
154: Games - Get Open Public Games

**Client Dependencies:**
#16 Games - Cards

**Out of Scope:**
All other buttons, such as "Replay" are slated for a later version. Tool tips are also slated for a later version

**Comment by morganedmonds** [comment]
Need to update AC, box highlighting and join button (with or without lock)

Move tool tips to other ticket.

**Comment by morganedmonds** [comment]
Updated AC per new reqs.

**Comment by morganedmonds** [comment]
Looks good, moving to design review.
