### ISSUE TITLE
Feature - Dynamic simulator configuration

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-web-client#198]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**

In the simulator, users cannot change their wombats or arena templates. 

**- Why you need it**

More flexible simulator

**- How it should work**

- Allow users to select wombat and simulator template

**Comment by emilyseibert** [comment]
We demo'd this.
