### ISSUE TITLE
Preview - Join Game

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#20]
As a user, I would like to join a selected game.

AC:

- Modal displays with dropdown of Wombats in user account
- User must select a color before clicking "Join"; Wombat thumbnail shows highlighted state when selected
- Any colors that have already been selected by another user are greyed out and non-clickable
- "Join" becomes available when all fields are selected
- User is added to the game upon clicking "Join"

Zplin:
https://zpl.io/Z1qmeMx

Notes:
Note that the designs do not include a field for password
Max players is set at 8, and we may eventually need to find a way to scale that visually

Potential Error States:
- No wombat selection
- No color selected
- Game is filled
- Where should the error states show for each input? inline?
- Adjust height of modal to accommodate error

Out of Scope:
- If the game is private, the user must enter the password for the game; this will be implemented in a separate ticket.- User cannot join game if the game is already full; alert is presented to the user matching https://zpl.io/Z28MGXf

**Comment by morganedmonds** [comment]
Updated AC to handle unavailable colors. This will be dependent on API ticket number 206.

**Comment by morganedmonds** [comment]
Need to test with more than one user in a game.

**Comment by morganedmonds** [comment]
Looks good according to all of the AC, closing.
