### ISSUE TITLE
Feature - Reusable select components

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-web-client#200]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**

- Reusable select components

**- Why you need it**

- Improved code quality 

**- How it should work**

![image](https://cloud.githubusercontent.com/assets/4649439/23559224/3f8e1eea-0004-11e7-8847-040f763e4acc.png)

**Comment by emilyseibert** [comment]
From CP:
I feel like it would be better for us to eventually make it so our components only take two arguments a props (which would be an object) and then the child. This would make this look like:

[submit-modal-input {:on-click close-modal} "OKAY"]
I think this matches the hiccup form more and would help with methods that have lots of parameters.

This isn't something we should address in this PR, but just wanted to write the comment and see your thoughts.

**Comment by morganedmonds** [comment]
This looks good to me. I took a look at all dropdowns, i.e. Join modal and Simulator configuration, and they look consistent and function as expected. The only note is that the font on the simulator configuration is different, but I imagine that is outside the scope of this ticket. Moving to Ready for Prod.
