### ISSUE TITLE
[Refactor] DB Games Refactor

### ISSUE THREAD

**Issue by dehli** [willowtreeapps/wombats-web-client#202]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## REFACTOR REQUEST
- I think it would make more sense for our games to be stored in a map where the ids are the keys. 
- This will be beneficial b/c it will allow us to keep the states stored in a common area. 
- We'd also be able to get rid of `:game/info`, `:game/arena`, etc. and just store it there.

**Comment by dehli** [comment]
I need to make sure that games are stored in db by id and not stored in an array (which is what happens when using `group-by`. Will need to switch to `reduce` or `reduce-kv`

**Comment by emilyseibert** [comment]
This has been implemented and working correctly (Games worked on Friday)
