### ISSUE TITLE
Preview - Game Layout

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#21]
As a user, I would like to view the game preview screen upon selecting a game.

AC:

- Hardcoded countdown timer 
- Join button
- Type of game
- Number of bots currently in game / capacity
- List of Wombats joined in game 
- Static preview of the arena (initial state)

Zeplin: https://zpl.io/Z1jJoq6

Out of Scope:
- Dynamic countdown timer will be handled in a separate ticket

**Comment by morganedmonds** [comment]
@morganedmonds add dependencies to this ticket.

**Comment by dehli** [comment]
*States*
1. Game running that you're in.
2. Game running that you're not in.
3. Winner declared for a game you're in.
4. Winner declared for a game you're not in.
5. Game count down for a game you're in.
6. Game count down for a game you're not in (and can join).
7. Game count down for a game you're not in (and can't join).
8. Game replay (after you dismiss the winner modal).

**Comment by emilyseibert** [comment]
Are previews of the game unavailable if you can't join? I.E. the game is filled or private.

**Comment by dehli** [comment]
Good question. I was thinking the preview was available, but when you press join the password modal would come up.

**Comment by morganedmonds** [comment]
I agree with CP, it would be great to be able to watch a game that I haven't joined.

**Comment by dehli** [comment]
**Still left:**

1. Autoscroll chat messages
2. Make title show countdown timer, and rounds (rounds require API update).
3. Make it so canvas is displayed nicely.
4. Broadcast players when you first go to a game (requires API update as well).

**Comment by morganedmonds** [comment]
Re: CP's comment, 1, 2, 4 & 5 are complete, #3 is a future feature

**Comment by dehli** [comment]
The third feature was addressed in #131
