### ISSUE TITLE
Simulator - Fog asset

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-web-client#211]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**

Official fog asset from design 

**- Why you need it**

Right now I have a temp asset in place to represent fog.

**Comment by emilyseibert** [comment]
assets uploaded: https://www.dropbox.com/home/Battle%20Bots/Assets

**Comment by morganedmonds** [comment]
I'm gonna hold off on closing this until #317 is resolved so that I can do a check in the Wombat view. Looks good in the full arena view.

**Comment by morganedmonds** [comment]
Tested on wombat view as well, looks good to me. Wouldn't hurt to get a design review from @jprehodick and/or @rebekah-russell . This is what it looks like in the Wombat view:

<img width="623" alt="screen shot 2017-03-24 at 3 28 40 pm" src="https://cloud.githubusercontent.com/assets/25081733/24310541/b5b68d66-10a6-11e7-9899-cd56bd346611.png">
