### ISSUE TITLE
Gameplay - Dynamic Ranking

### ISSUE THREAD

**Issue by jasonye85** [willowtreeapps/wombats-web-client#25]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
As a user, I would like to see the highest scoring Wombat ranked at the top of the status bar.

**- Why you need it**
Dynamic ranking makes it easy for users to see which Wombats are winning the game at a point in gameplay.

**- How it should work**
* Players are ordered dynamically by overall score

**Comment by morganedmonds** [comment]
This requires some sort of stats or scoring. We can push this to V2. For V1, the list of Wombats on the game play screen will be static.

**Comment by morganedmonds** [comment]
This has been completed as a part of another ticket. Players are dynamically ranked by score. There is no animation. Closing.
