### ISSUE TITLE
[BUG] Join modal dropdown broken by disabled color overlay z index

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#275]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## ISSUE DESCRIPTION
**- What version of the project are you using?**
Alpha1

**- What browser and its version are you using?**
Chrome most up to date

**- What did you do? (Steps to Replicate Issue)**
Attempt to select a wombat after someone has joined a game

**- What did you expect to see?**
The dropdown looking normal on top of the colors

**- What did you see instead?**
The dropdown is broken by the black overlay on disabled colors

**Comment by morganedmonds** [comment]
This looks good! Dropdown looks as expected over a greyed-out Wombat in the join modal.
