### ISSUE TITLE
Access the web client with Key

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#278]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
A way to access the website, insert a key, gain access to login (or create an account). Once you have an account, you should be able to by pass key entry. 

**- Why you need it**
Controlled release

**- How it should work**
* hit wombats.io
* Enter Key or Login like normal 
* redirected to `/beta?beta_key=xyz`
* Api Logins you in and checks for key validation
* if it works, access to app
* if it doesn't, back to welcome, maybe show error

Need designs from jesse

**Comment by emilyseibert** [comment]
blocked by https://github.com/willowtreeapps/wombats-api/issues/325 @oconn

**Comment by emilyseibert** [comment]
feature/web-client-access
- missing flipping through languages
- needs testing with db

**Comment by morganedmonds** [comment]
Seeing a minor issue with this:

Steps to Repro:
1. Make sure that you are logged out of Github
2. On the landing page, click on "Get Started Now" without entering an access code
-> No error is shown. The user is navigated to Github login. 
3. Log in through Github  to be redirected back to the landing page
-> Error is shown asking the user to enter a correct access key

This could be a frustrating experience for a new user. Is there a way to check the access key before the user is redirected to Github auth? 

@emilyseibert

**Comment by morganedmonds** [comment]
I've written up #312 for the issue described above. Since the scope of this ticket has been met, I'm closing.
