### ISSUE TITLE
Game Management - Arena List

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#282]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
![image](https://cloud.githubusercontent.com/assets/16102717/23864790/022f1f7a-07ea-11e7-8f3c-fbb5c6383957.png)
No edit, no add.

**- Why you need it**
To view arenas to create games

**- How it should work**
* Table of arenas like image above.

**Comment by morganedmonds** [comment]
Jesse will update the designs based on configurable fields and numbers (not h, m, l)

**Comment by emilyseibert** [comment]
feature/arena-table
- needs polished design implementation

**Comment by morganedmonds** [comment]
@emilyseibert @jprehodick Do we want to include perimeter as a column in the arena table? Maybe with an attribute of either on or off? 

This is the current view:
<img width="1112" alt="screen shot 2017-03-21 at 12 22 18 pm" src="https://cloud.githubusercontent.com/assets/25081733/24157927/33643268-0e31-11e7-8847-b153b4d586bf.png">

**Comment by jprehodick** [comment]
If this is something that we the admin team and the recruiting team think is important to see here, then I don't have a problem adding it. Personally, I don't think I really care about seeing this /shrug

**Comment by morganedmonds** [comment]
Ok! Closing this issue for now. We can open a new issue if the recruiting team seems interested in adding the column.
