### ISSUE TITLE
Query Params Broken 

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-web-client#293]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## ISSUE DESCRIPTION
**- What version of the project are you using?**

1.0.0-alpha1

**- What browser and its version are you using?**

Chrome

**- What did you do? (Steps to Replicate Issue)**

Query params are not being properly parsed by secretary

**- What did you expect to see?**

Query param parsing

**- What did you see instead?**

**- More details?**

https://github.com/gf3/secretary/issues/63

We may need to migrate from pushy to googles html pushstate to get this working. 

This is causing pattern matching to not work in the router which will cause problems with pagination as well.

**Comment by morganedmonds** [comment]
This needs to go into alpha-2, updating milestone.
