### ISSUE TITLE
Incorrect Winner

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#307]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## ISSUE DESCRIPTION
**- What version of the project are you using?**
Latest QA

**- What browser and its version are you using?**
Version 55.0.2883.95 (64-bit)

**- What did you do? (Steps to Replicate Issue)**
Play a game. 

**- What did you expect to see?**
Copycatz should have won with the highest score.

**- What did you see instead?**
Pickles won with the least amount of points.. may have been one of the only bots alive. Winner function error.

**- More details?**
![image](https://cloud.githubusercontent.com/assets/16102717/24154347/49c6d3b2-0e27-11e7-9c8f-1f51ec680396.png)

**Comment by emilyseibert** [comment]
Bug on 3.21.2017 QA release

**Comment by morganedmonds** [comment]
Ran a few different games, and this seems to be working correctly now. Moving to Ready for Prod.
