### ISSUE TITLE
Unable to trigger "join" event for private games

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-web-client#310]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## ISSUE DESCRIPTION
**- What version of the project are you using?**

Alpha1 (Develop Head)

**- What browser and its version are you using?**

Chrome

**- What did you do? (Steps to Replicate Issue)**

- Create private game
- Click game card
- Fill out form
- Attempt to join

**- What did you expect to see?**

- User joins game, modal closes

**- What did you see instead?**

- Nothing appeared to happen. Checked the network tab, not join event fired.

**- More details?**

No

**Comment by morganedmonds** [comment]
Fixed! Moving to closed.
