### ISSUE TITLE
Code changes not taking effect in simulator

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/wombats-web-client#311]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## ISSUE DESCRIPTION
**- What version of the project are you using?**

Aplha1 (dev)

**- What browser and its version are you using?**

Chrome

**- What did you do? (Steps to Replicate Issue)**

- Load wombat into simulator
- Adjust code
- Run

**- What did you expect to see?**

Changes take place

**- What did you see instead?**

No changes are captured

**- More details?**

**Comment by morganedmonds** [comment]
After some clarification from CP for me, this is working as expected!
