### ISSUE TITLE
Minimap Simulator

### ISSUE THREAD

**Issue by dehli** [willowtreeapps/wombats-web-client#317]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## ISSUE DESCRIPTION
**- What version of the project are you using?**
- Alpha 1 (after game-state refactor)

**- What browser and its version are you using?**
- Chrome

**- What did you do? (Steps to Replicate Issue)**
- Go to simulator, press view wombat view

**- What did you expect to see?**
- Wombat's view

**- What did you see instead?**
- Full arena view

**Comment by morganedmonds** [comment]
Yay fixed! Closing.
