### ISSUE TITLE
Games - Screen

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#32]
As a user, I would like to view all open games and games that I have joined.

**AC:**
* The Game Lobby displays upon clicking Games in the nav bar
* The user can toggle between "Open" and "Joined" (see designs)
* Games displayed in the Open tab have a status of open and have not been joined by the user
* Games displayed in the Joined tab have been joined by the current user, regardless of status
* Games are sorted by creation date - most to least recent
* Empty states match designs

**Zeplin:**
https://zpl.io/Z4F9Fg

Out of Scope:
Search and pagination is slated for v2 (or v3)

**Comment by morganedmonds** [comment]
Updated AC according to new designs.

**Comment by emilyseibert** [comment]
Games can't be sorted by creation date yet. I'm not sent that information by the API

**Comment by emilyseibert** [comment]
I'm going to temporarily have the app database push newly created games to the top, but this is a temporarily fix. I'd rather the db return a sorted list or provide a timestamp for sort. @oconn

**Comment by morganedmonds** [comment]
Since the AC for this ticket have been met, I'm closing this ticket. We will need to create a new ticket during refinement for Game Lobby v2 according to Jesse's revised designs. See #124.
