### ISSUE TITLE
QA Branch Issues 7-31

### ISSUE THREAD

**Issue by elibosley** [willowtreeapps/wombats-web-client#350]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

**Bugs Found**

- [x] Clicking games twice causes the page selector to stop being highlighted and the query params to come out of the URL bar

- [x] Issues with ace external function calls

**Comment by elibosley** [comment]
@dehli What should we do with this now that this is merged in?

**Comment by dehli** [comment]
I'll close it after I verify that it's been fixed.

**Comment by dehli** [comment]
Verified fixed on http://qa.wombats.io
