### ISSUE TITLE
Framework - Add Socket Support

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#37]
This is a lower priority, but including this ticket for tracking.

**Comment by oconn** [comment]
A majority of the initial groundwork has been complete for this. Some things that are still outstanding though;

- Keep alive message must be sent in order to keep the socket open. This should be sent at a regular interval, the server will close connections after around 5 mins of inactivity.

**Comment by oconn** [comment]
Added support for the keep alive messages in API #194

**Comment by morganedmonds** [comment]
Assuming this is working as expected based on Oconn's comments, moving to closed.
