### ISSUE TITLE
Config - Arenas Table Hover State

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#93]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
As an admin or event coordinator, I would like to hover over an arena name to view available actions in the Arenas table.

**- Why you need it**
View actions.

**- How it should work**

* Hovering over an arena name highlights the full row in grey 
* Hovering over an arena name shows the "Delete", "Edit" and "Create Game" buttons for all arenas 

**- Zeplin**
https://zpl.io/17G3Lb
Note that the design is missing the Delete button

**Comment by emilyseibert** [comment]
No longer Deleting and Editing.

**Comment by morganedmonds** [comment]
This looks good to me! We can get @jprehodick 's eyes on it during a design review to get the final verdict.
