### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#98]
As an unauthenticated user, I would like to be greeted and prompted to sign in.

AC:

* Upon navigating to wombats.io as an unauthenticated user, display welcome page to the user (according to designs)
* The only clickable element is the CTA prompting the user to sign-in
* Clicking "Start Playing Now" triggers the Github auth workflow
* Successful authentication returns the user to the "My Wombats" screen
* Background is a video of the arena (provided by Jesse)

Zeplin:
https://zpl.io/ZfEFBw

Out of Scope:
Onboarding experience will go into v2 (or v3)

**Comment by dehli** [comment]
Hey @BinLiuWTA, figured I'd assign this to you. Feel free to update the ticket with any progress/questions!

**Comment by BinLiuWTA** [comment]
Thanks !

**Comment by morganedmonds** [comment]
Note - @jesseprehodick requested that the background be a video - @BinLiuWTA  will need a video asset (.png or .mpg sequence) in order to complete this ticket. Updating AC accordingly.

**Comment by morganedmonds** [comment]
Hey @BinLiuWTA we'd like to ultimately have a dynamic background, but if you are working on this now, a placeholder static image should be fine. Let me know if you need  more information.

@dehli eventually could help you hook in the actual arena to display that in the background to make sure it always matches the latest design.

**Comment by BinLiuWTA** [comment]
Hi Morgan,

I didn't do much last week on this ticket, barely have env setup for it. I
have a high priority ticket for marketing related to willowtree website
today, I will dive in more tonight on this issue. Will that be OK? Sorry
about the slow progress!!!

Bin

**Comment by dehli** [comment]
Hey @BinLiuWTA, ya that's fine! Feel free to work on this whenever you get around to it. If you'd like some help getting stuff setup make sure you reach out to one of us!

**Comment by BinLiuWTA** [comment]
Thanks! CP!!
Bin

**Comment by morganedmonds** [comment]
@BinLiuWTA @emilyseibert I'm not seeing the landing page in QA, should I be?

**Comment by emilyseibert** [comment]
it's on my qa, weird

**Comment by morganedmonds** [comment]
@emilyseibert hmmm ok i'm seeing it in incognito, i'll do some more testing and see if i can figure out a pattern.

**Comment by emilyseibert** [comment]
@morganedmonds auth bug - i have a fix and will get that into qa

**Comment by morganedmonds** [comment]
Ok update - I had to clear my browsing data in Chrome to see it, even after logging out of Github and restarting my browser. 

@emilyseibert thanks!
